#!/usr/bin/perl -w

use strict;
use Math::Primality qw/is_prime/;
use Benchmark;

my $magnitude = 10;
my @small_nums = map { int(rand() * 10 ** $magnitude) } (1..50);

print "Psuedorandom numbers of magnitude 10 ^ $magnitude\n";

timethis(1000, sub {is_prime("$_") for @small_nums});
